{{- range .Values.data }}
{{- $name :=  (printf "%s-%s" (include "go-chive.fullname" $) (.name)) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "go-chive.labels" $ | nindent 4 }}
  annotations:    
    {{- if $.Values.annotations }}
    {{- toYaml $.Values.annotations | indent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      {{- include "go-chive.labels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        {{- include "go-chive.labels" $ | nindent 8 }}
    spec:
      serviceAccountName: {{ $.Values.serviceAccountName }}
      containers:
        - name: go-chive
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          env:
          - name: AGE_LIMIT
            value: "{{ .ageLimit }}"
          - name: ARCHIVE_CHECK_INTERVAL
            value: "{{ .archiveCheckInterval }}"
          - name: COLLECTION
            value: "{{ .collection }}"
          - name: DATABASE
            value: "{{ .database }}"
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ $.Values.secretName }}"
                key: levit_admin
          - name: S3_BUCKET_URI
            value: "{{ .s3.bucket }}"
          - name: S3_UPLOAD_INTERVAL
            value: "{{ .s3.uploadInterval }}"
          - name: ARCHIVE_FIELD
            value: "{{ .archiveField }}"
          - name: HOST_ADDRESS
            value: "{{ .hostAddress }}"
          args:
            - -age-limit=$(AGE_LIMIT)
            - -archive-check-interval=$(ARCHIVE_CHECK_INTERVAL)
            - -collection=$(COLLECTION)
            - -database=$(DATABASE)
            - -host=mongodb+srv://<username>:$(PASSWORD)@$(HOST_ADDRESS).db.bumhwak.test.com/?tls=false
            - -s3-bucket-uri=$(S3_BUCKET_URI)
            - -s3-upload-interval=$(S3_UPLOAD_INTERVAL)
            - -archive-field=$(ARCHIVE_FIELD)
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
      affinity:
        {{- toYaml $.Values.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml $.Values.nodeSelector | nindent 8 }}
      {{- if $.Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      tolerations:
        {{- toYaml $.Values.tolerations | nindent 8 }}
      imagePullPolicy: {{ $.Values.image.pullPolicy }}
{{- end -}}
