apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-chive-deployment
  labels:
    app: go-chive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-chive
  template:
    metadata:
      labels:
        app: go-chive
    spec:
      serviceAccountName: db-manager-account
      containers:
      - name: go-chive
        image: 999999999999.dkr.ecr.ap-northeast-2.amazonaws.com/db/go-chive:1.0
        env:
        - name: AGE_LIMIT
          value: "1d"
        - name: ARCHIVE_CHECK_INTERVAL
          value: "60"
        - name: COLLECTION
          value: "test"
        - name: DATABASE
          value: "test"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-admin-secret
              key: admin
        - name: S3_BUCKET_URI
          value: "database-backup/test/"
        - name: S3_UPLOAD_INTERVAL
          value: "180"
        - name: ARCHIVE_FIELD
          value: "createdAt"
        args:
        - -age-limit=$(AGE_LIMIT)
        - -archive-check-interval=$(ARCHIVE_CHECK_INTERVAL)
        - -collection=$(COLLECTION)
        - -database=$(DATABASE)
        - -host=mongodb+srv://admin:$(PASSWORD)@test.db.prod.test.com/?tls=false
        - -s3-bucket-uri=$(S3_BUCKET_URI)
        - -s3-upload-interval=$(S3_UPLOAD_INTERVAL)
        - -archive-field=$(ARCHIVE_FIELD)
        - -queryLimit 1000
