apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-db-admin-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: prod-db-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin
      remoteRef:
        key: prod/db/admin
        property: admin
